export const REQUEST_PHOTOS_START = 'REQUEST_PHOTOS_START';
export const REQUEST_PHOTOS_FAIL = 'REQUEST_PHOTOS_FAIL';
export const REQUEST_PHOTOS_FINISH = 'REQUEST_PHOTOS_FINISH';

export const MODAL_RESET_IMAGE_LIST = 'MODAL_RESET_IMAGE_LIST';
export const ADD_NEW_CARD = 'ADD_NEW_CARD';
export const REMOVE_CARD = 'REMOVE_CARD';

export const ADD_NEW_BOARD = 'ADD_NEW_BOARD';
export const CHANGE_COLUMN_TITLE = 'CHANGE_COLUMN_TITLE';
export const REMOVE_COLUMN = 'REMOVE_COLUMN';
export const SET_BACKGROUND_IMAGE = 'SET_BACKGROUND_IMAGE';
export const ADD_NEW_COLUMN = 'ADD_NEW_COLUMN';
export const ON_DRAG_END = 'ON_DRAG_END';

export const ADD_NEW_COMMENT = 'ADD_NEW_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
