export const REQUEST_PHOTOS_START = 'REQUEST_PHOTOS_START';
export const REQUEST_PHOTOS_FAIL = 'REQUEST_PHOTOS_FAIL';
export const REQUEST_PHOTOS_FINISH = 'REQUEST_PHOTOS_FINISH';

export const MODAL_RESET_IMAGE_LIST = 'MODAL_RESET_IMAGE_LIST';
export const ADD_NEW_CARD = 'ADD_NEW_CARD';

export const ADD_NEW_BOARD = 'ADD_NEW_BOARD';
export const CHANGE_COLUMN_TITLE = 'CHANGE_COLUMN_TITLE';
export const SET_BACKGROUND_IMAGE = 'SET_BACKGROUND_IMAGE';
export const ADD_NEW_COLUMN = 'ADD_NEW_COLUMN';
export const ON_DRAG_END = 'ON_DRAG_END';
