export const SEARCHBAR_CHANGE = 'SEARCHBAR_CHANGE';

export const REQUEST_PHOTOS_START = 'REQUEST_PHOTOS_START';
export const REQUEST_PHOTOS_FAIL = 'REQUEST_PHOTOS_FAIL';
export const REQUEST_PHOTOS_FINISH = 'REQUEST_PHOTOS_FINISH';

export const SET_BACKGROUND_IMAGE = 'SET_BACKGROUND_IMAGE';

export const MODAL_RESET_IMAGE_LIST = 'MODAL_RESET_IMAGE_LIST';
