const ADD_NEW_BOARD = 'ADD_NEW_BOARD';
const CHANGE_COLUMN_TITLE = 'CHANGE_COLUMN_TITLE';
const SET_BACKGROUND_IMAGE = 'SET_BACKGROUND_IMAGE';
const ADD_NEW_COLUMN = 'ADD_NEW_COLUMN';
const ON_DRAG_END = 'ON_DRAG_END';
export default {
	ADD_NEW_BOARD,
	SET_BACKGROUND_IMAGE,
	CHANGE_COLUMN_TITLE,
	ON_DRAG_END,
	ADD_NEW_COLUMN,
};
